import { Persona, WebsiteAnalysis } from "./types";

/**
 * Mock personas for the hebammen (midwife) website demo.
 * In production, these would be generated by Gemini based on scraped website content.
 */
export const MOCK_ANALYSIS: WebsiteAnalysis = {
  url: "https://www.kmw-technology.de/hebammen",
  productName: "Hebammen-Service Platform",
  productDescription:
    "A digital platform connecting expectant mothers with professional midwife services. Offers birth preparation courses, postnatal care, and comprehensive pregnancy support in the local area.",
  targetAudience:
    "Pregnant women and new parents in Germany seeking midwife services, birth preparation, and postnatal support.",
  keyFeatures: [
    "Midwife matching & booking",
    "Birth preparation courses",
    "Postnatal care coordination",
    "Pregnancy information & resources",
    "Online appointment scheduling",
    "Local midwife directory",
  ],
  industry: "Healthcare / Maternal Care",
};

export const MOCK_PERSONAS: Persona[] = [
  {
    id: "p1",
    name: "Maria Schmidt",
    age: 29,
    role: "First-time expectant mother",
    background:
      "Software developer in Berlin, 28 weeks pregnant. Methodical researcher who reads every review before booking anything. New to the city, no family nearby.",
    segment: "First Pregnancy",
    icon: "pregnant_woman",
    painPoints: [
      "Overwhelmed by amount of information online",
      "Hard to find available midwives in her area",
      "Unsure what services she actually needs",
    ],
    goals: [
      "Find a reliable midwife before 32 weeks",
      "Attend birth preparation classes",
      "Feel prepared and supported",
    ],
    techSavviness: "high",
    selected: true,
  },
  {
    id: "p2",
    name: "Sarah Weber",
    age: 34,
    role: "Mother expecting second child",
    background:
      "Part-time teacher in Hamburg, has a 3-year-old. Had a difficult first birth experience and wants better support this time. Already knows what questions to ask.",
    segment: "Experienced Mother",
    icon: "family_restroom",
    painPoints: [
      "Previous midwife retired, needs a new one",
      "Wants someone who takes her birth trauma seriously",
      "Scheduling conflicts with work and childcare",
    ],
    goals: [
      "Find a midwife experienced with VBAC",
      "Get postnatal support including for her toddler",
      "Better birth experience than last time",
    ],
    techSavviness: "medium",
    selected: true,
  },
  {
    id: "p3",
    name: "Tom Richter",
    age: 32,
    role: "Expectant father",
    background:
      "Project manager in Munich. Partner is 20 weeks pregnant. Wants to be actively involved but feels excluded from most pregnancy resources.",
    segment: "Partner / Support",
    icon: "person",
    painPoints: [
      "Most platforms seem designed only for mothers",
      "Doesn't know how to best support his partner",
      "Wants to attend courses but feels awkward",
    ],
    goals: [
      "Find couple-friendly birth prep courses",
      "Understand what to expect during birth",
      "Be a useful support person",
    ],
    techSavviness: "high",
    selected: true,
  },
  {
    id: "p4",
    name: "Ayşe Yılmaz",
    age: 26,
    role: "Expectant mother, immigrant background",
    background:
      "Originally from Turkey, living in Stuttgart for 4 years. 16 weeks pregnant. Good German but prefers clear, simple language. Limited knowledge of the German healthcare system.",
    segment: "International / Expat",
    icon: "public",
    painPoints: [
      "Confused by the German Hebamme system",
      "Language barriers in medical settings",
      "No family in Germany for support",
    ],
    goals: [
      "Understand what a Hebamme does vs. a doctor",
      "Find a midwife who speaks Turkish or simple German",
      "Navigate Krankenkasse coverage for midwife services",
    ],
    techSavviness: "medium",
    selected: true,
  },
  {
    id: "p5",
    name: "Lena Bauer",
    age: 38,
    role: "Late-career first-time mother",
    background:
      "Management consultant in Frankfurt. High-risk pregnancy due to age. Very organized, expects premium service quality. Used to solving problems by throwing money at them.",
    segment: "Premium / High-risk",
    icon: "workspace_premium",
    painPoints: [
      "Worried about complications due to age",
      "Hard to find midwives experienced with high-risk pregnancies",
      "Wants immediate availability and responsiveness",
    ],
    goals: [
      "Find a highly experienced midwife ASAP",
      "Comprehensive monitoring and support plan",
      "One-on-one prenatal classes, not group sessions",
    ],
    techSavviness: "high",
    selected: true,
  },
  {
    id: "p6",
    name: "Julia Fischer",
    age: 22,
    role: "Young student, unplanned pregnancy",
    background:
      "University student in Heidelberg. Unplanned pregnancy at 12 weeks. Tight budget, relies on Bafög. Anxious and unsure about everything.",
    segment: "Young / Budget-conscious",
    icon: "school",
    painPoints: [
      "Worried about affording prenatal care",
      "Embarrassed to ask basic questions",
      "No idea where to even start",
    ],
    goals: [
      "Confirm everything is covered by insurance",
      "Find a non-judgmental midwife",
      "Get practical, step-by-step guidance",
    ],
    techSavviness: "high",
    selected: true,
  },
  {
    id: "p7",
    name: "Claudia Müller",
    age: 41,
    role: "Mother of three, seeking postnatal care",
    background:
      "Stay-at-home mom in a rural area near Freiburg. Just had her third child. Exhausted, needs pelvic floor rehab and breastfeeding support. Limited options locally.",
    segment: "Postnatal / Rural",
    icon: "cottage",
    painPoints: [
      "Very few midwives available in her rural area",
      "Long wait times for Rückbildung courses",
      "Needs home visits but lives 30min from nearest town",
    ],
    goals: [
      "Get breastfeeding support within the first week",
      "Find Rückbildungskurs she can attend with baby",
      "Home visit option for postnatal check-ups",
    ],
    techSavviness: "low",
    selected: true,
  },
  {
    id: "p8",
    name: "Nina Hoffmann",
    age: 31,
    role: "Natural birth advocate",
    background:
      "Yoga teacher in Cologne. Very health-conscious, wants a home birth with minimal medical intervention. Active in online birth communities.",
    segment: "Natural / Alternative",
    icon: "self_improvement",
    painPoints: [
      "Hard to find midwives who support home births",
      "Feels judged by mainstream medical community",
      "Insurance complications for home birth coverage",
    ],
    goals: [
      "Find a Beleghebamme for a home birth",
      "Holistic birth preparation including hypnobirthing",
      "Strong rapport with her midwife pre-birth",
    ],
    techSavviness: "medium",
    selected: true,
  },
  {
    id: "p9",
    name: "Katrin Wagner",
    age: 35,
    role: "Returning expat",
    background:
      "Lived in the US for 8 years, just moved back to Germany. 24 weeks pregnant. Used to the American OB/GYN model and finds the German midwife system confusing but intriguing.",
    segment: "Returning Expat",
    icon: "flight_land",
    painPoints: [
      "Doesn't understand the Hebamme vs. doctor split",
      "Used to one-stop-shop OB/GYN model",
      "Feels behind on finding a midwife at 24 weeks",
    ],
    goals: [
      "Quickly understand the German prenatal care model",
      "Find a midwife who can explain the system",
      "Catch up on what she should have done by now",
    ],
    techSavviness: "high",
    selected: false,
  },
  {
    id: "p10",
    name: "Andrea Braun",
    age: 44,
    role: "Grandmother seeking info for daughter",
    background:
      "Retired nurse in Dresden. Her 25-year-old daughter just announced pregnancy. Wants to help but knows the system has changed since her time.",
    segment: "Family Support",
    icon: "elderly_woman",
    painPoints: [
      "Information online seems contradictory",
      "Doesn't want to overstep with her daughter",
      "Unsure about modern practices vs. what she remembers",
    ],
    goals: [
      "Find reliable, current information to share",
      "Help her daughter find a good midwife",
      "Understand what has changed in prenatal care",
    ],
    techSavviness: "low",
    selected: false,
  },
];
