import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#c0c7d5",
        "on-secondary-fixed": "#001453",
        background: "#131316",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#004884",
        "secondary-fixed": "#dde1ff",
        "on-primary-container": "#002a52",
        "inverse-surface": "#e4e1e5",
        "primary-fixed": "#d4e3ff",
        "inverse-primary": "#005fad",
        outline: "#8a919e",
        "tertiary-fixed": "#c2f35b",
        "surface-container-highest": "#353437",
        "on-tertiary-container": "#202e00",
        "on-secondary": "#09277d",
        "tertiary-fixed-dim": "#a7d641",
        "on-primary": "#00315d",
        "outline-variant": "#404753",
        secondary: "#b8c4ff",
        "on-primary-fixed": "#001c39",
        "on-secondary-container": "#a4b5ff",
        "tertiary-container": "#749e00",
        error: "#ffb4ab",
        "surface-dim": "#131316",
        "primary-container": "#3492f6",
        "surface-container": "#1f1f22",
        "surface-container-lowest": "#0e0e11",
        "on-tertiary": "#253600",
        "secondary-container": "#2b4297",
        tertiary: "#a7d641",
        "primary-fixed-dim": "#a4c9ff",
        "on-tertiary-fixed": "#141f00",
        surface: "#131316",
        "inverse-on-surface": "#303033",
        "on-error-container": "#ffdad6",
        "on-surface": "#e4e1e5",
        "on-background": "#e4e1e5",
        "on-secondary-fixed-variant": "#294094",
        "surface-variant": "#353437",
        "surface-bright": "#39393c",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#374e00",
        "surface-tint": "#a4c9ff",
        "secondary-fixed-dim": "#b8c4ff",
        "surface-container-high": "#2a2a2d",
        primary: "#a4c9ff",
        "surface-container-low": "#1b1b1e",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;
